FROM postgres:13.1

RUN \
rm -rf \
    /usr/share/postgresql/$PG_MAJOR/postgresql.conf.sample \
    /usr/share/postgresql/$PG_MAJOR/pg_hba.conf.sample \
    /usr/share/postgresql/$PG_MAJOR/pg_ident.conf.sample \
    /var/lib/apt/lists/* \
    /tmp/pear

COPY ./conf/postgresql.conf /usr/share/postgresql/$PG_MAJOR/postgresql.conf.sample
COPY ./conf/pg_hba.conf /usr/share/postgresql/$PG_MAJOR/pg_hba.conf.sample
COPY ./conf/pg_ident.conf /usr/share/postgresql/$PG_MAJOR/pg_ident.conf.sample

RUN \
chmod -R 644 \
    /usr/share/postgresql/$PG_MAJOR/postgresql.conf.sample \
    /usr/share/postgresql/$PG_MAJOR/pg_hba.conf.sample \
    /usr/share/postgresql/$PG_MAJOR/pg_ident.conf.sample \
&& rm -rf \
       /var/lib/apt/lists/* \
       /tmp/pear